[project]
name = "easegress-mcp"
version = "0.1.0"
description = "A Model Context Protocol server implementation for operations on Easegress."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["mcp[cli]>=1.6.0"]
